/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

/* This is a generated file, do not edit */

#ifndef CONDITIONS_STRING_HPP
#define CONDITIONS_STRING_HPP

const char* SourceTypeOrReferenceIdString[]
{
    "CONDITION_SOURCE_TYPE_NONE",
    "CONDITION_SOURCE_TYPE_CREATURE_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_DISENCHANT_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_FISHING_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_GAMEOBJECT_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_ITEM_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_MAIL_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_MILLING_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_PICKPOCKETING_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_PROSPECTING_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_REFERENCE_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_SKINNING_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_SPELL_LOOT_TEMPLATE",
    "CONDITION_SOURCE_TYPE_SPELL_IMPLICIT_TARGET",
    "CONDITION_SOURCE_TYPE_GOSSIP_MENU",
    "CONDITION_SOURCE_TYPE_GOSSIP_MENU_OPTION",
    "CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE",
    "CONDITION_SOURCE_TYPE_SPELL",
    "CONDITION_SOURCE_TYPE_SPELL_CLICK_EVENT",
    "CONDITION_SOURCE_TYPE_QUEST_ACCEPT",
    "CONDITION_SOURCE_TYPE_QUEST_SHOW_MARK",
    "CONDITION_SOURCE_TYPE_VEHICLE_SPELL",
    "CONDITION_SOURCE_TYPE_SMART_EVENT",
    "CONDITION_SOURCE_TYPE_MAX"
};

const char* ConditionTypeOrReferenceString[]
{
    "CONDITION_NONE",
    "CONDITION_AURA",
    "CONDITION_ITEM",
    "CONDITION_ITEM_EQUIPPED",
    "CONDITION_ZONEID",
    "CONDITION_REPUTATION_RANK",
    "CONDITION_TEAM",
    "CONDITION_SKILL",
    "CONDITION_QUESTREWARDED",
    "CONDITION_QUESTTAKEN",
    "CONDITION_DRUNKENSTATE",
    "CONDITION_WORLD_STATE",
    "CONDITION_ACTIVE_EVENT",
    "CONDITION_INSTANCE_DATA",
    "CONDITION_QUEST_NONE",
    "CONDITION_CLASS",
    "CONDITION_RACE",
    "CONDITION_ACHIEVEMENT",
    "CONDITION_TITLE",
    "CONDITION_SPAWNMASK",
    "CONDITION_GENDER",
    "CONDITION_UNUSED_21",
    "CONDITION_MAPID",
    "CONDITION_AREAID",
    "CONDITION_UNUSED_24",
    "CONDITION_SPELL",
    "CONDITION_PHASEMASK",
    "CONDITION_LEVEL",
    "CONDITION_QUEST_COMPLETE",
    "CONDITION_NEAR_CREATURE",
    "CONDITION_NEAR_GAMEOBJECT",
    "CONDITION_OBJECT_ENTRY",
    "CONDITION_TYPE_MASK",
    "CONDITION_RELATION_TO",
    "CONDITION_REACTION_TO",
    "CONDITION_DISTANCE_TO",
    "CONDITION_ALIVE",
    "CONDITION_HP_VAL",
    "CONDITION_HP_PCT",
    "CONDITION_MAX"
};

#endif
